# This is the newer version

FROM node:20-alpine

WORKDIR /app

# Accept build arguments from DigitalOcean
ARG VITE_SWITCHLY_HOST
ARG VITE_SWITCHLY_API_PORT
ARG VITE_SWITCHLY_MIDGARD_PORT
ARG VITE_ETHEREUM_RPC_URL
ARG VITE_ETHEREUM_CHAIN_ID
ARG VITE_SWITCHLY_API_BASE_URL
ARG VITE_SWITCHLY_MIDGARD_BASE_URL
ARG VITE_STELLAR_HORIZON_URL
ARG VITE_STELLAR_SOROBAN_URL
ARG VITE_SWITCHLY_SERVICE_WS
ARG VITE_DEV_SERVER_PORT

# Set environment variables for the build process
ENV VITE_SWITCHLY_HOST=$VITE_SWITCHLY_HOST
ENV VITE_SWITCHLY_API_PORT=$VITE_SWITCHLY_API_PORT
ENV VITE_SWITCHLY_MIDGARD_PORT=$VITE_SWITCHLY_MIDGARD_PORT
ENV VITE_ETHEREUM_RPC_URL=$VITE_ETHEREUM_RPC_URL
ENV VITE_ETHEREUM_CHAIN_ID=$VITE_ETHEREUM_CHAIN_ID
ENV VITE_SWITCHLY_API_BASE_URL=$VITE_SWITCHLY_API_BASE_URL
ENV VITE_SWITCHLY_MIDGARD_BASE_URL=$VITE_SWITCHLY_MIDGARD_BASE_URL
ENV VITE_STELLAR_HORIZON_URL=$VITE_STELLAR_HORIZON_URL
ENV VITE_STELLAR_SOROBAN_URL=$VITE_STELLAR_SOROBAN_URL
ENV VITE_SWITCHLY_SERVICE_WS=$VITE_SWITCHLY_SERVICE_WS
ENV VITE_DEV_SERVER_PORT=$VITE_DEV_SERVER_PORT

COPY package.json .

# Clean install without package-lock to get latest compatible versions
RUN npm install

# Force clean reinstall of problematic packages
RUN npm uninstall esbuild vite @vitejs/plugin-react-swc
RUN npm install esbuild@latest vite@latest @vitejs/plugin-react-swc@latest

COPY . .

# Debug: Print environment variables during build
RUN echo "=== Environment Variables Debug ===" && \
    echo "VITE_SWITCHLY_HOST: $VITE_SWITCHLY_HOST" && \
    echo "VITE_SWITCHLY_API_PORT: $VITE_SWITCHLY_API_PORT" && \
    echo "VITE_SWITCHLY_MIDGARD_PORT: $VITE_SWITCHLY_MIDGARD_PORT" && \
    echo "VITE_ETHEREUM_RPC_URL: $VITE_ETHEREUM_RPC_URL" && \
    echo "VITE_ETHEREUM_CHAIN_ID: $VITE_ETHEREUM_CHAIN_ID" && \
    echo "VITE_SWITCHLY_API_BASE_URL: $VITE_SWITCHLY_API_BASE_URL" && \
    echo "VITE_SWITCHLY_MIDGARD_BASE_URL: $VITE_SWITCHLY_MIDGARD_BASE_URL" && \
    echo "VITE_STELLAR_HORIZON_URL: $VITE_STELLAR_HORIZON_URL" && \
    echo "VITE_STELLAR_SOROBAN_URL: $VITE_STELLAR_SOROBAN_URL" && \
    echo "VITE_SWITCHLY_SERVICE_WS: $VITE_SWITCHLY_SERVICE_WS" && \
    echo "VITE_DEV_SERVER_PORT: $VITE_DEV_SERVER_PORT" && \
    echo "==================================="

# Build with environment variables available (skip type checking for Docker build)
RUN npx vite build

EXPOSE 8080

CMD [ "node", "proxy-server.js" ]